
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import ScrollUpBtn from "@/components/ScrollUpBtn";


export const metadata = {
  title: "Voltic.ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk&display=swap" rel="stylesheet"/>
      </head>
      <body
        
      >
        <main>
        <Navbar/>
        {children}
        <Footer/>
        <ScrollUpBtn/>
        </main>
      </body>
    </html>
  );
}
